### ISSUE TITLE
How to run it with IntelliJ IDEA

### ISSUE THREAD

**Issue by sinadarvi** [bascan/kotlin-js-example#1]
hi,
i'm new to kotlin-js and I was wondering how can i run this project w/ IntelliJ IDEA.
if you please provide a tutorial or intro to do that will be awesome.
thanks

**Comment by bascan** [comment]
Hi, you can run the gradle build from within your IntelliJ workspace. Please see the following help article for details: https://www.jetbrains.com/help/idea/create-run-debug-configuration-for-gradle-tasks.html
